Spring:
  cloud:
    refresh:
      refreshable: none # 解决降低boot和cloud版本数据源循环注入问题
server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: chenzihan
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.182.129
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo