server:
  port: 8083
spring:
  application:
    name: search-service
  rabbitmq:
    host: 192.168.182.129
    virtual-host: /leyou
    username: leyou
    password: leyou
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.182.129:9300
  jackson:
    default-property-inclusion: non_null # 响应json数据时，忽略为null的字段
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10 # 拉取服务过期时间
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15 # 10秒不发送就过期
