server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10 # 拉取路由时间间隔
zuul:
  prefix: /api
  routes:
    item-service: /item/**  # 添加商品微服务
    search-service: /search/** # 添加搜索微服务
    user-service: /user/** # 添加用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务
  add-host-header: true # 请求转发时携带域名
  sensitive-headers: # 覆盖敏感头信息，使cookie可以正常写入
leyou:
  jwt:
    pubKeyPath: D:\\IdeaProjects\\leyou\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item